name: Build and push latest

on:
  # cron job to trigger the build on any push to master
  push:
    #branches:
    #- "master"
    #    paths:
    #      - 'pihole-unbound/VERSION'
  schedule:
    # cron job to trigger the build dialy (time in UTC)
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Check_version:
    name: Compare original pihole and pihole unbound docker versions
    runs-on: ubuntu-latest
    outputs:
      run_build_jobs: ${{ steps.set_output.outputs.run_jobs }}
      pihole_version: ${{ steps.pihole_version.outputs.release }}
    steps:
      - name: Get latest release of pihole docker
        uses: rez0n/actions-github-release@main
        id: pihole_version
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "pi-hole/docker-pi-hole"
          type: "latest"

      - name: Get latest release of pihole unbound docker
        uses: rez0n/actions-github-release@main
        id: pihole_unbound_version
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "VijayakumarRavi/docker-pihole-unbound"
          type: "latest"

      - name: compare versions and set output
        id: set_output
        run: |
          if [[${{ steps.pihole_version.outputs.release }} != ${{ steps.pihole_unbound_version.outputs.release }}]]; then
            echo "run_jobs=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_jobs=false" >> "$GITHUB_OUTPUT"
          fi

  docker:
    name: Build 🏗 & Publish 🚀
    needs: [Check_version]
    if: needs.Check_version.outputs.run_build_jobs == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.Check_version.outputs.pihole_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          build-args: ${{ needs.Check_version.outputs.pihole_version }}, ${{ secrets.GITCRED }}
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: vijaysrv/pihole-unbound:beta,vijaysrv/pihole-unbound:${{ needs.Check_version.outputs.pihole_version }}-beta

      - name: Creating release
        uses: ncipollo/release-action@v1
