name: workflow run cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workflow runs
        uses: iamludal/action-purge-workflow-runs@v2
        with:
          days-old: 14
          ignore-open-pull-requests: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}